"""Plain-string templates for EU AI Act Art. 53 / Annex IV evidence generation.

No Jinja — stdlib str.format() only, avoiding the template-injection exec surface.
All template constants are module-level so they are trivially testable and deterministic.
"""

from __future__ import annotations

# ---------------------------------------------------------------------------
# Art. 53 / Annex XII Training-Data Summary template
# ---------------------------------------------------------------------------

ART53_TEMPLATE = """\
# EU AI Act Art. 53 / Annex XII — Training-Data Summary

**Model:** {model_name}
**Provider / Organisation:** {provider}
**Base model:** {base_model}
**Version / Run ID:** {run_id}
**Generated:** {generated_at}
**BOM content hash:** `{bom_hash}`

---

## 1. Data Overview

| Field | Value |
|---|---|
| Total records | {total_records} |
| Number of data components | {num_components} |
| Modalities | {modalities} |

## 2. Data Source Categories

{source_categories_table}

## 3. Top Domains by Crawl Volume ({domain_threshold_pct}% threshold)

{domain_section}

## 4. Copyright / Opt-Out Handling

{optout_section}

## 5. PII & Contamination Controls

{pii_section}

## 6. Attestation

This summary was generated from a signed Model Passport.

| Field | Value |
|---|---|
| Attestation algorithm | {attest_algorithm} |
| Key ID | {attest_key_id} |
| Signed at | {attest_signed_at} |
| Passport signature | `{attest_signature}` |

---
*Generated by Provenir — regulation-as-code. This document evidences provenance captured
at training time; it does not constitute legal compliance advice.*
"""

# ---------------------------------------------------------------------------
# Annex IV Technical File template
# ---------------------------------------------------------------------------

ANNEX_IV_TEMPLATE = """\
# EU AI Act Annex IV — Technical Documentation

**Model:** {model_name}
**Base model:** {base_model}
**Version / Run ID:** {run_id}
**Generated:** {generated_at}
**BOM content hash:** `{bom_hash}`

---

## §1 General Description

{section1}

## §2(a) Development Methods and Process

{section2a}

## §2(b) Design Specifications

{section2b}

## §2(c) Data Provenance

{section2c}

## §2(d) Validation and Testing

{section2d}

## §3 Monitoring and Logging Capabilities

{section3}

## §4 Risk Management

{section4}

## §5 Changes Over Lifecycle

{section5}

## §6 Standards Applied

{section6}

## §7 Post-Market Monitoring

{section7}

## §8 Human Oversight Design

{section8}

## §9 Conformity Assessment

{section9}

---

## Coverage Summary

**Score:** {coverage_score:.1%} ({satisfied_count}/{total_count} fields satisfied)

{coverage_table}

---
*Generated by Provenir — regulation-as-code. Fields marked MISSING require
organisational input that cannot be derived from the BOM alone.*
"""

# ---------------------------------------------------------------------------
# FDA PCCP (Predetermined Change Control Plan) template
# ---------------------------------------------------------------------------

FDA_PCCP_TEMPLATE = """\
# FDA PCCP — AI/ML Software as a Medical Device (SaMD)
# Predetermined Change Control Plan

**Model:** {model_name}
**Base model:** {base_model}
**Version / Run ID:** {run_id}
**Generated:** {generated_at}
**BOM content hash:** `{bom_hash}`

---

## 1. Device Description

{device_description}

## 2. SaMD Function

{samd_function}

## 3. Training Data Documentation

{training_data_documentation}

## 4. Performance Testing

{performance_testing}

## 5. Real-World Performance Monitoring

{real_world_monitoring}

## 6. Impact Assessment

{impact_assessment}

## 7. Description of Anticipated Changes

{change_description}

## 8. Version Control and Traceability

{version_control}

---

## Coverage Summary

**Score:** {coverage_score:.1%} ({satisfied_count}/{total_count} fields satisfied)

{coverage_table}

---
*Generated by Provenir — regulation-as-code. Fields marked MISSING require
organisational or BOM input that cannot be derived automatically.*
"""

# ---------------------------------------------------------------------------
# NIST AI RMF 1.0 template
# ---------------------------------------------------------------------------

NIST_AI_RMF_TEMPLATE = """\
# NIST AI Risk Management Framework (AI RMF 1.0) — Evidence Summary

**Model:** {model_name}
**Base model:** {base_model}
**Version / Run ID:** {run_id}
**Generated:** {generated_at}
**BOM content hash:** `{bom_hash}`

---

## GOVERN — Organizational Accountability and Culture

### GOVERN.1 — Policies and Accountability

{govern_1}

### GOVERN.2 — Organizational Practices

{govern_2}

---

## MAP — Risk Identification and Classification

### MAP.1 — Risk Identification

{map_1}

### MAP.2 — Scientific Basis and Reproducibility

{map_2}

### MAP.3 — Impact Assessment

{map_3}

---

## MEASURE — Analysis and Assessment

### MEASURE.1 — Performance Testing

{measure_1}

### MEASURE.2 — Bias and Fairness

{measure_2}

### MEASURE.3 — Reward Validity

{measure_3}

---

## MANAGE — Prioritize and Address Risks

### MANAGE.1 — Incident Response

{manage_1}

### MANAGE.2 — Model Lifecycle

{manage_2}

---

## Coverage Summary

**Score:** {coverage_score:.1%} ({satisfied_count}/{total_count} fields satisfied)

{coverage_table}

---
*Generated by Provenir — regulation-as-code. Fields marked MISSING or PARTIAL
indicate areas requiring organisational process documentation beyond BOM data.*
"""

__all__ = ["ART53_TEMPLATE", "ANNEX_IV_TEMPLATE", "FDA_PCCP_TEMPLATE", "NIST_AI_RMF_TEMPLATE"]
