from __future__ import annotations

from pathlib import Path


class ModelCardGenerator:
    """Generate a minimal markdown model card for a trained adapter or model."""

    def __init__(self, output_dir: str | Path) -> None:
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def generate(self, model_name: str, description: str) -> Path:
        card_path = self.output_dir / f"{model_name}.md"
        notes = (
            "- Generated by Provenir\n"
            "- Review dataset provenance and evaluation before deployment.\n"
        )
        card_content = f"# {model_name}\n\n## Description\n{description}\n\n## Notes\n{notes}"
        card_path.write_text(card_content, encoding="utf-8")
        return card_path
